/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces.HAdministration;

import Business.EcoSystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.NetWork.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.UtilPersonnel.ErrorPerson;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aki
 */
public class ReportListjPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportListjPanel
     */
    JPanel container;
    UserAccount ua;
    Organization organization;
    Enterprise enterprise;
    EcoSystem es;

    public ReportListjPanel(JPanel container, UserAccount ua, Organization org, Enterprise enterpirse, EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.organization = org;
        this.enterprise = enterpirse;
        es = ecoSystem;
        //populateTable();
        populateCombox();
    }

    private void populateCombox() {
        for (Network n : es.getNetworkList()) {
            for (Enterprise enter : n.getEd().getEnterprisesList()) {
                if (enter.equals(enterprise)) {
                    for (Enterprise enterpriss : n.getEd().getEnterprisesList()) {
                        if (enterpriss instanceof HospitalEnterprise || enterpriss instanceof ClinicEnterprise) {
                            enterprisejComboBox1.addItem(enterpriss);
                        } else {
                          return;
                        }
                    }
                }
            }
        }
    }

    private void populateEnterpriseTable(Enterprise e) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (WorkRequest workRequest : e.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = workRequest;
            row[1] = workRequest.getSenderEnterprise();
            row[2] = workRequest.getLevel1();
            model.addRow(row);

        }

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList()) {
            if (workRequest.getInvestigationresule().equals("app")) {
                Object[] row = new Object[3];
                row[0] = workRequest;
                row[1] = workRequest.getSenderEnterprise();
                row[2] = workRequest.getLevel2();
                model.addRow(row);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewdetailjButton2 = new javax.swing.JButton();
        specificjTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        generaljTextField8 = new javax.swing.JTextField();
        satijTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorpersonjTable2 = new javax.swing.JTable();
        sourcejTextField1 = new javax.swing.JTextField();
        enterprisejComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        viewalljButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        dateoferrorjTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Report List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 25, 168, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Report Date", "Hospital Name", "Medial Error"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Hospital Name");
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Medial Error");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 633, 281));

        viewdetailjButton2.setText("View Detail");
        viewdetailjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailjButton2ActionPerformed(evt);
            }
        });
        add(viewdetailjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));
        add(specificjTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 240, -1));

        jLabel8.setText("Specific ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel9.setText("General Medical Error");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));
        add(generaljTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 240, -1));
        add(satijTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 240, -1));

        jLabel11.setText("Satisfation ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        backjButton1.setText("back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        errorpersonjTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Related Personnel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(errorpersonjTable2);
        if (errorpersonjTable2.getColumnModel().getColumnCount() > 0) {
            errorpersonjTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 161, 106));
        add(sourcejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 240, -1));

        enterprisejComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisejComboBox1ActionPerformed(evt);
            }
        });
        add(enterprisejComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        jLabel2.setText("Enterprise name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        viewalljButton2.setText("View all Report");
        viewalljButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewalljButton2ActionPerformed(evt);
            }
        });
        add(viewalljButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jLabel13.setText("Date of Error");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, 20));
        add(dateoferrorjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 240, -1));

        jLabel14.setText("Location:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, -1, 30));

        jLabel15.setText("Source");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void viewdetailjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailjButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        } else {
            WorkRequest workRequest = (WorkRequest) jTable1.getValueAt(selectedRow, 0);
            generaljTextField8.setText(workRequest.getLevel1());
            specificjTextField6.setText(workRequest.getLevel2());
            dateoferrorjTextField2.setText(workRequest.getDateoferror().toString());
            if (workRequest.getSatisfylevel() != null) {
                if (workRequest.getSatisfylevel().equals("YES")) {
                    satijTextField9.setText(workRequest.getSatisfylevel());

                } else {
                    satijTextField9.setText(workRequest.getSatisfylevel());
                    satijTextField9.setForeground(Color.red);
                }

            } else {
                satijTextField9.setText("NOT EVALUTATED");
            }

            sourcejTextField1.setText(workRequest.getSource());
            jTextField1.setText(workRequest.getLocation());
           // level2jTextField1.setText(workRequest.getLevel2());

            DefaultTableModel model = (DefaultTableModel) errorpersonjTable2.getModel();
            model.setRowCount(0);
            for (ErrorPerson errorPerson : workRequest.getEpd().getErrorpersonlist()) {
                Object[] row = new Object[1];
                row[0] = errorPerson;
                model.addRow(row);

            }
        }
        //personneljTextField7.setText(workRequest.getPersonnel());
    }//GEN-LAST:event_viewdetailjButton2ActionPerformed

    private void enterprisejComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisejComboBox1ActionPerformed
        // TODO add your handling code here:
        populateEnterpriseTable((Enterprise) enterprisejComboBox1.getSelectedItem());
    }//GEN-LAST:event_enterprisejComboBox1ActionPerformed

    private void viewalljButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewalljButton2ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_viewalljButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField dateoferrorjTextField2;
    private javax.swing.JComboBox enterprisejComboBox1;
    private javax.swing.JTable errorpersonjTable2;
    private javax.swing.JTextField generaljTextField8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField satijTextField9;
    private javax.swing.JTextField sourcejTextField1;
    private javax.swing.JTextField specificjTextField6;
    private javax.swing.JButton viewalljButton2;
    private javax.swing.JButton viewdetailjButton2;
    // End of variables declaration//GEN-END:variables
}
