/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import UserInterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Util.ErrorUtil;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class Level1UnsafeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Level1UnsafeJPanel
     */
    
    Enterprise enterprise;
    JPanel container;
    UserAccount ua;
    WorkRequest workRequset;
    Organization o;
    EcoSystem ecoSystem;

    public Level1UnsafeJPanel(JPanel container, WorkRequest workRequest, Enterprise e, UserAccount ua, Organization organization, EcoSystem ecoSystem1) {
        initComponents();
        this.container = container;
        this.workRequset = workRequest;
        this.ua = ua;
        this.enterprise = e;
        this.o = organization;
        this.ecoSystem = ecoSystem1;
        
        
        int progrss = 75;
       jProgressBar1.setValue(progrss);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Unsafe Condition:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 270, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setText("Device");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 40));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton2.setText("Fall");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 40));

        jButton6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton6.setText("Surgery or Anesthesia");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 40));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 671, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 690, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 610, 10));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 460, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        workRequset.setLevel2(ErrorUtil.DEVICE_OR_MEDICAL);
        Level2DeviceErrorJPanel patientReportError2Panel = new Level2DeviceErrorJPanel(container, workRequset, enterprise, ua,o,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", patientReportError2Panel);
        cl.next(container);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        workRequset.setLevel2(ErrorUtil.FALL);

        Level2FallJPanel doctorReportFallJPanel = new Level2FallJPanel(container, workRequset, enterprise, ua,o,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("DoctorReportFallJPanel", doctorReportFallJPanel);
        cl.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        workRequset.setLevel2(ErrorUtil.SURGERY_OR_ANESTHESIA);
        Level2SurgeryJPanel drsjp = new Level2SurgeryJPanel(container, workRequset, enterprise, ua,o,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("doctorReportMedicationJPanel", drsjp);
        cl.next(container);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
