/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import UserInterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Util.ErrorUtil;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class Level1NearMissPanel extends javax.swing.JPanel {

    /**
     * Creates new form Level1NearMissPanel
     */
    Enterprise e;
    JPanel container;
    UserAccount ua;
    WorkRequest workRequset;
    Organization o;
    EcoSystem ecoSystem;

    public Level1NearMissPanel(JPanel container, WorkRequest workRequest, Enterprise e, UserAccount ua, Organization organization, EcoSystem ecoSystem1) {
        initComponents();
        this.container = container;
        this.workRequset = workRequest;
        this.ua = ua;
        this.e = e;
        this.o = organization;
        this.ecoSystem = ecoSystem1;
        
        int progrss = 75;
       jProgressBar1.setValue(progrss);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        jLabel1.setText("Near Miss");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 470, -1));

        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setText("Blood or Blood Product");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, 40));

        jButton4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton4.setText("Medication or other substance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, 40));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setText("Device");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 40));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 681, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 640, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setText("Near Miss");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 225, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 640, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        workRequset.setLevel2(ErrorUtil.BLOOD_OR_BLOOD_PRODUCT);

        Level2BloodErrorJPanel patientReportError2Panel = new Level2BloodErrorJPanel(container, workRequset, e, ua, o, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", patientReportError2Panel);
        cl.next(container);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        workRequset.setLevel2(ErrorUtil.MEDICATION_OR_OTHER);
        Level2MedicationJPanel doctorReportMedicationJPanel = new Level2MedicationJPanel(container, workRequset, e, ua, o, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("doctorReportMedicationJPanel", doctorReportMedicationJPanel);
        cl.next(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        workRequset.setLevel2(ErrorUtil.DEVICE_OR_MEDICAL);
        Level2DeviceErrorJPanel patientReportError2Panel = new Level2DeviceErrorJPanel(container, workRequset, e, ua, o, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", patientReportError2Panel);
        cl.next(container);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
