/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class PatientHomepageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientHomepageJPanel
     */
    JPanel container;
    EcoSystem ecoSystem;
    PatientOrganization patientorg;
    Enterprise enterprise;
    UserAccount ua;

    public PatientHomepageJPanel(JPanel container, EcoSystem ecoSystem, Organization org, Enterprise enterprise, UserAccount ua) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.patientorg = (PatientOrganization)org;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        populateText();

    }
    private void populateText(){
        unamejTextField2.setText(ua.getUserName());
       // namejTextField3.setText(ua.getPatient().getPatientname());
        hosnamejTextField4.setText(enterprise.getOrgName());
        rolejTextField5.setText(ua.getRole().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unamejTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hosnamejTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rolejTextField5 = new javax.swing.JTextField();
        checkjButton2 = new javax.swing.JButton();
        reportjButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Report - Patient Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Your Information");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Username:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 30));

        unamejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unamejTextField2ActionPerformed(evt);
            }
        });
        add(unamejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Hospital name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));
        add(hosnamejTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 220, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Role:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));
        add(rolejTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 220, -1));

        checkjButton2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        checkjButton2.setText("Check Report");
        checkjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkjButton2ActionPerformed(evt);
            }
        });
        add(checkjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        reportjButton1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        reportjButton1.setText("Report");
        reportjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportjButton1ActionPerformed(evt);
            }
        });
        add(reportjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorRole/Screen Shot 2013-12-10 at 4.44.26 PM.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 420, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void checkjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkjButton2ActionPerformed
        // TODO add your handling code here:
        CheckStatusPjPanel checkStatuJPanel = new CheckStatusPjPanel(container, ua, enterprise, ecoSystem,patientorg);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("setMessageJPanel", checkStatuJPanel);
        cl.next(container);
    }//GEN-LAST:event_checkjButton2ActionPerformed

    private void reportjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportjButton1ActionPerformed
        // TODO add your handling code here:
        StartReportErrorJPanel patientinfoJPanel = new StartReportErrorJPanel(container, ua, patientorg, enterprise, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("dirjp", patientinfoJPanel);
        cl.next(container);
    }//GEN-LAST:event_reportjButton1ActionPerformed

    private void unamejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unamejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unamejTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkjButton2;
    private javax.swing.JTextField hosnamejTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton reportjButton1;
    private javax.swing.JTextField rolejTextField5;
    private javax.swing.JTextField unamejTextField2;
    // End of variables declaration//GEN-END:variables
}
