/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.Util.Source;
import Business.WorkQueue.PatientReport;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class StartReportErrorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartReportErrorJPanel
     */
    JPanel container;
    UserAccount ua;
    PatientOrganization patientOrganization;
    EcoSystem business;
    Enterprise e;

    public StartReportErrorJPanel(JPanel container, UserAccount ua, PatientOrganization organization, Enterprise e1, EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.patientOrganization = organization;
        this.e = e1;
        business = ecoSystem;

        int progrss = 25;
        jProgressBar1.setValue(progrss);            
        
        phonejTextField2.setText("");
        populateInfo();
    }

     private void populateInfo() {
        if(ua.getPatient().getPatientEmail()!=null){
            emailjTextField3.setText(ua.getPatient().getPatientEmail());
            phonejTextField2.setText(String.valueOf(ua.getPatient().getPatientPhone()));
        }if(ua.getPatient().getPatientEmail()==null){
            emailjTextField3.setText("");
            phonejTextField2.setText("");
           
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        emailjTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phonejTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nextjButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        firstjCheckBox1 = new javax.swing.JCheckBox();
        secondjCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Please fill the personal information");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 350, -1));

        emailjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextField3ActionPerformed(evt);
            }
        });
        add(emailjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 181, 180, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Email:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 181, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Phone:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 231, -1, -1));

        phonejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonejTextField2ActionPerformed(evt);
            }
        });
        add(phonejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 231, 180, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Your information will be confidential.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 277, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("The contact information will help us contact you for futher information");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 307, -1, -1));

        nextjButton1.setText("Next");
        nextjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButton1ActionPerformed(evt);
            }
        });
        add(nextjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, -1, -1));

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Select the Date of Medical Error:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 398, 330, -1));

        firstjCheckBox1.setText("First Hand");
        firstjCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstjCheckBox1ActionPerformed(evt);
            }
        });
        add(firstjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 120, -1));

        secondjCheckBox3.setText("Second Hand");
        secondjCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondjCheckBox3ActionPerformed(evt);
            }
        });
        add(secondjCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Resource:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 110, -1));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 200, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, -1, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 650, 690, 10));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 470, 40));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void emailjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextField3ActionPerformed

    private void phonejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonejTextField2ActionPerformed

    private void nextjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButton1ActionPerformed
        // TODO add your handling code here:

        PatientReport patientReport = new PatientReport();
        patientReport.setSender(ua);
        patientReport.setPatientreporter(ua);
        patientReport.setStatus("Pending");
        Date date = jDateChooser1.getDate();
        patientReport.setDateoferror(date);
        try {
            patientReport.creatTime();
        } catch (ParseException ex) {
            Logger.getLogger(StartReportErrorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (firstjCheckBox1.isSelected()) {
            patientReport.setSource(Source.FIRST);
        }
        if (secondjCheckBox3.isSelected()) {
            patientReport.setSource(Source.SECOND);
        }

        patientReport.setSenderEnterprise(e);
       // Enterprise en = patientReport.getSenderEnterprise();
        //en.getIssuesWorkRequestList().add(patientReport);

        Patient patient = ua.getPatient();

        if (ua.getPatient().getPatientEmail() == null) {
            patient.setPatientEmail(emailjTextField3.getText());
        }

        if (ua.getPatient().getPatientPhone() == 0) {
            patient.setPatientPhone(Integer.parseInt(phonejTextField2.getText()));
        }

        PatientReportWorkAreaJPanel doctorWorkareaJPanel = new PatientReportWorkAreaJPanel(container, ua, patientOrganization, e, business, patientReport);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("setMessageJPanel", doctorWorkareaJPanel);
        cl.next(container);
    }//GEN-LAST:event_nextjButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void firstjCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstjCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstjCheckBox1ActionPerformed

    private void secondjCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondjCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondjCheckBox3ActionPerformed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailjTextField3;
    private javax.swing.JCheckBox firstjCheckBox1;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton nextjButton1;
    private javax.swing.JTextField phonejTextField2;
    private javax.swing.JCheckBox secondjCheckBox3;
    // End of variables declaration//GEN-END:variables
}
