/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
     JPanel container;
     Enterprise enterprise;
     UserAccount ua;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel( JPanel container, Enterprise enterprise,UserAccount ua) {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.ua = ua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganization = new javax.swing.JButton();
        manageEmployee = new javax.swing.JButton();
        manageUserAccount = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 33, 269, -1));

        manageOrganization.setText("Manage Organization");
        manageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationActionPerformed(evt);
            }
        });
        add(manageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        manageEmployee.setText("Manage Employee");
        manageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeActionPerformed(evt);
            }
        });
        add(manageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        manageUserAccount.setText("manageUserAccount");
        manageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountActionPerformed(evt);
            }
        });
        add(manageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jButton1.setText("Register Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationActionPerformed
        ManageOrganizationJPanel manageOrganizationJPanel=new ManageOrganizationJPanel(container, enterprise.getOrganizationDirectory(),enterprise);
        CardLayout cl=(CardLayout) container.getLayout();
        container.add("ManageOrganizationJPanel",manageOrganizationJPanel);
        cl.next(container);
    }//GEN-LAST:event_manageOrganizationActionPerformed

    private void manageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeActionPerformed
      
        ManageEmployeeJPanel manageEmployeeJPanel=new ManageEmployeeJPanel(container,enterprise.getOrganizationDirectory());
         CardLayout cl=(CardLayout) container.getLayout();
        container.add("manageEmployeeJPanel",manageEmployeeJPanel);
        cl.next(container);
    }//GEN-LAST:event_manageEmployeeActionPerformed

    private void manageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountActionPerformed
       ManageUserAccountJPanel manageUserAccountJPanel=new ManageUserAccountJPanel(container,enterprise.getOrganizationDirectory());
       CardLayout cl=(CardLayout) container.getLayout();
        container.add("manageUserAccountJPanel",manageUserAccountJPanel);
        cl.next(container);
    }//GEN-LAST:event_manageUserAccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         HandleRegisterRequestJPanel handleRegisterRequestJPanel=new HandleRegisterRequestJPanel(container,ua);
       CardLayout cl=(CardLayout) container.getLayout();
        container.add("manageUserAccountJPanel",handleRegisterRequestJPanel);
        cl.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployee;
    private javax.swing.JButton manageOrganization;
    private javax.swing.JButton manageUserAccount;
    // End of variables declaration//GEN-END:variables
}
