/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdminRole;


import Business.Organization.Organization;
import Business.RegisterReport.RegisterReport;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aki
 */
public class HandleRegisterRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HandleRegisterRequestJPanel
     */
    JPanel container;
    UserAccount ua;
    public HandleRegisterRequestJPanel(JPanel container, UserAccount ua) {
        initComponents();
        this.ua = ua;
        this.container = container;
        populateTable();
        
        
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        
        for(RegisterReport registerReport:ua.getRegisterReportDirectory().getRegisterReportList()){
            Object[] row = new Object[4];
            row[0] = registerReport;
           // row[1] = registerReport.getName();
            row[1] = registerReport.getNetwork();
            row[2] = registerReport.getEnterprise();
            row[3] = registerReport.getOrganization();
            
             model.addRow(row);
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backjButton3 = new javax.swing.JButton();
        approvejButton1 = new javax.swing.JButton();
        delincejButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Network", "Enterprise", "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Register Request List");

        backjButton3.setText("back");
        backjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton3ActionPerformed(evt);
            }
        });

        approvejButton1.setText("Approve");
        approvejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvejButton1ActionPerformed(evt);
            }
        });

        delincejButton2.setText("Decline");
        delincejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delincejButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(backjButton3)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(approvejButton1)
                            .addGap(52, 52, 52)
                            .addComponent(delincejButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backjButton3)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delincejButton2)
                    .addComponent(approvejButton1))
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton3ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_backjButton3ActionPerformed

    private void delincejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delincejButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        }else{
            RegisterReport registerReport = (RegisterReport) jTable1.getValueAt(selectedRow, 0);
            registerReport.setApproveOrNot("delince");
            
        }
        
    }//GEN-LAST:event_delincejButton2ActionPerformed

    private void approvejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvejButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        }else{
            RegisterReport registerReport = (RegisterReport) jTable1.getValueAt(selectedRow, 0);
            Organization userOrganization = registerReport.getOrganization();
            UserAccount uaa = userOrganization.getUserAccountDirectory().createUserAccount();
            uaa.setUserName(registerReport.getUsername());
            uaa.setPassword(registerReport.getPassword());
            uaa.setRole(registerReport.getRole());
            
            if(uaa.getRole().toString().equals("Business.Role.PatientRole")){
                uaa.getPatient().setPatientname(registerReport.getRegisterpatient().getPatientname());    
            }if(uaa.getRole().toString().equals("Business.Role.DoctorRole")){
                uaa.getDoctor().setDoctorname(registerReport.getRegisterdoctor().getDoctorname());
                
            }
            
        }
         
        
    }//GEN-LAST:event_approvejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvejButton1;
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton backjButton3;
    private javax.swing.JButton delincejButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
