/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Doctor.Doctor;
import Business.GovEmployee.GovEmployee;
import Business.Organization.DoctorOrganization;
import Business.Organization.HAdminstration;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PatientOrganization;
import Business.Organization.SecretaryOrganization;
import Business.Organization.ServiceOrganization;
import Business.Patient.Patient;
import Business.Servicer.Servicer;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aki
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeJPanel
     */
    JPanel container;
    OrganizationDirectory organizationDirectory;

    public ManageEmployeeJPanel(JPanel container, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.container = container;
        this.organizationDirectory = organizationDirectory;
        populateOrganization();
    }

    private void populateOrganization() {
        for (Organization org : organizationDirectory.getOrganizationList()) {
            jComboBox2.addItem(org);
            jComboBox1.addItem(org);
        }

    }

    private void createEmployee() {
        Organization org = (Organization) jComboBox1.getSelectedItem();

        if (org instanceof DoctorOrganization) {
            String name = jTextField1.getText();
            org.getDoctorDirectory().createDoctor(name);
        }
        if (org instanceof PatientOrganization) {
            String name = jTextField1.getText();
            org.getPatientDirectory().createPtient(name);

        }
        if (org instanceof ServiceOrganization) {
            String name = jTextField1.getText();
            org.getServicerDirectory().createServicer(name);

        }if(org instanceof SecretaryOrganization || org instanceof HAdminstration){
            String name = jTextField1.getText();
            org.getGed().createGovEmployee(name);
        }
    }

    private void populateEmployeeTable(Organization organization) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (organization instanceof PatientOrganization) {
            for (Patient patient : organization.getPatientDirectory().getPatientList()) {
                Object[] row = new Object[1];
                row[0] = patient;
                model.addRow(row);

            }
        }
        if (organization instanceof ServiceOrganization) {
            for (Servicer s : organization.getServicerDirectory().getServicerList()) {
                Object[] row = new Object[1];
                row[0] = s;
                model.addRow(row);
            }
        }
        if (organization instanceof DoctorOrganization) {
            for (Doctor d : organization.getDoctorDirectory().getDoctorList()) {
                Object[] row = new Object[1];
                row[0] = d;
                model.addRow(row);
            }

        }if(organization instanceof SecretaryOrganization || organization instanceof HAdminstration ){
            for(GovEmployee ge: organization.getGed().getGovEmployeeList()){
                   Object[] row = new Object[1];
                row[0] = ge;
                model.addRow(row);
                
            }
            
        }
           // else{
           //for (Employee emploee : organization.getEmployeeDirectory().getEmployeeList()) {
            //Object[] row = new Object[1];
            //row[0] = emploee;
            //row[1] = emploee.getEmpName();
           // model.addRow(row);

          
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 50, 375, 213));

        jLabel1.setText("Person name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 357, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 351, 245, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 290, 232, -1));

        jLabel2.setText("Organization");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 294, -1, -1));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 441, -1, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 11, 218, -1));

        jLabel3.setText("Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 15, -1, -1));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 441, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        populateEmployeeTable((Organization) jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        createEmployee();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
