/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Util.Reportsatifty;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aki
 */
public class DCheckStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DCheckStatusJPanel
     */
    JPanel container;
    UserAccount ua;
    DoctorOrganization org;
    EcoSystem business;
    Enterprise e;

    public DCheckStatusJPanel(JPanel container, UserAccount ua, Organization org, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.org = (DoctorOrganization) org;
        this.e = enterprise;
        business = ecoSystem;
        populatestatus();
        populatesatisfy();

    }

    private void populatesatisfy() {
        satifisfyjComboBox1.addItem(Reportsatifty.YES);
        satifisfyjComboBox1.addItem(Reportsatifty.NO);

    }

    private void populatestatus() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (WorkRequest request : ua.getWorkQueue().getWorkRequestList()) {

            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getStatus();
            row[2] = request.getLevel2();
            
            

            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        viewrespondjButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        satifisfyjComboBox1 = new javax.swing.JComboBox();
        submitjButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchtjButton3 = new javax.swing.JButton();
        searchjTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        resjTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("check status:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Time", "Status", "General Error"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 640, 151));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Respond from service center:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        viewrespondjButton1.setText("View Respond");
        viewrespondjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrespondjButton1ActionPerformed(evt);
            }
        });
        add(viewrespondjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Please select one row:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Are you satisfied with the respond: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        satifisfyjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satifisfyjComboBox1ActionPerformed(evt);
            }
        });
        add(satifisfyjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 150, -1));

        submitjButton2.setText("submit");
        submitjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton2ActionPerformed(evt);
            }
        });
        add(submitjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 131, -1));

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jButton4.setText("Chart Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, -1));

        searchtjButton3.setText("Search by number");
        searchtjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtjButton3ActionPerformed(evt);
            }
        });
        add(searchtjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 171, -1));
        add(searchjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 80, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        jLabel8.setText("Near Miss");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 470, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 740, -1));

        resjTextArea1.setColumns(20);
        resjTextArea1.setRows(5);
        jScrollPane2.setViewportView(resjTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewrespondjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrespondjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        } else {
            WorkRequest workRequest = (WorkRequest) jTable1.getValueAt(selectedRow, 0);
            if (workRequest.getRespond() != null) {
                resjTextArea1.setText(workRequest.getRespond());
            } else {
                resjTextArea1.setText("The Patient service center has not view the request yet");
            }
        }

    }//GEN-LAST:event_viewrespondjButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void satifisfyjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satifisfyjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satifisfyjComboBox1ActionPerformed

    private void submitjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        } else {
            WorkRequest workRequest = (WorkRequest) jTable1.getValueAt(selectedRow, 0);
           // workRequest.setStatus("");
            workRequest.setSatisfylevel((String) satifisfyjComboBox1.getSelectedItem());
        }
    }//GEN-LAST:event_submitjButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        populatestatus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        DoctorReportChartJPanel drcjp = new DoctorReportChartJPanel(container, ua, e, business);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("reportdataJPanel", drcjp);
        cl.next(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchtjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtjButton3ActionPerformed
        // TODO add your handling code here:
        int searchid = Integer.valueOf(searchjTextField1.getText());

        WorkQueue workQueue = ua.getWorkQueue();
        WorkRequest workRequest = workQueue.searchByID(searchid, ua, org);
        if (workRequest != null) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            Object[] row = new Object[3];
            row[0] = workRequest;
            row[1] = workRequest.getStatus();
            row[2] = workRequest.getLevel1();
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(null, "NOT FOUND");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchtjButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea resjTextArea1;
    private javax.swing.JComboBox satifisfyjComboBox1;
    private javax.swing.JTextField searchjTextField1;
    private javax.swing.JButton searchtjButton3;
    private javax.swing.JButton submitjButton2;
    private javax.swing.JButton viewrespondjButton1;
    // End of variables declaration//GEN-END:variables
}
