/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ServiceOrganization;
import Business.UserAccount.UserAccount;
import Business.Util.Blood;
import Business.Util.Location;
import Business.UtilPersonnel.ErrorPerson;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class DLevel2BloodErrorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DLevel2BloodErrorJPanel
     */
    JPanel container;
    WorkRequest workRequest;
    Enterprise e;
    UserAccount ua;
    Organization o;
    EcoSystem ecoSystem;

    public DLevel2BloodErrorJPanel(JPanel container, WorkRequest workRequest1, Enterprise e, UserAccount ua, Organization o,
            EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.workRequest = workRequest1;
        this.e = e;
        this.ua = ua;
        this.o = o;
        this.ecoSystem = ecoSystem;
       populateLocation();
        int progress = 100;
       jProgressBar1.setValue(progress);
    }

    
      private void populateLocation(){
        locationjComboBox1.removeAllItems();
        locationjComboBox1.addItem(Location.EMERGENCY);
        locationjComboBox1.addItem(Location.LABORATORY);
        locationjComboBox1.addItem(Location.OR);
        locationjComboBox1.addItem(Location.OUTPATIEN);
        locationjComboBox1.addItem(Location.PHARMACY);
        locationjComboBox1.addItem(Location.WARD);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productjCheckBox1 = new javax.swing.JCheckBox();
        redjCheckBox2 = new javax.swing.JCheckBox();
        plasmajCheckBox3 = new javax.swing.JCheckBox();
        rhlgjCheckBox4 = new javax.swing.JCheckBox();
        wholejCheckBox5 = new javax.swing.JCheckBox();
        samplejCheckBox6 = new javax.swing.JCheckBox();
        postjCheckBox7 = new javax.swing.JCheckBox();
        adminstrationjCheckBox1 = new javax.swing.JCheckBox();
        PhysiciansjCheckBox2 = new javax.swing.JCheckBox();
        nursejCheckBox3 = new javax.swing.JCheckBox();
        surgeonjCheckBox4 = new javax.swing.JCheckBox();
        pathologistjCheckBox5 = new javax.swing.JCheckBox();
        phajCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        locationjComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productjCheckBox1.setText("Product test or request");
        add(productjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        redjCheckBox2.setText("Red Blood Cells");
        add(redjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        plasmajCheckBox3.setText("Plasma");
        add(plasmajCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        rhlgjCheckBox4.setText("RHLG");
        add(rhlgjCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        wholejCheckBox5.setText("Whole Blood");
        add(wholejCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        samplejCheckBox6.setText("Sample");
        add(samplejCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        postjCheckBox7.setText("Post-transfusion");
        add(postjCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        adminstrationjCheckBox1.setText("Adminstration");
        adminstrationjCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminstrationjCheckBox1ActionPerformed(evt);
            }
        });
        add(adminstrationjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        PhysiciansjCheckBox2.setText("Physicians");
        PhysiciansjCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysiciansjCheckBox2ActionPerformed(evt);
            }
        });
        add(PhysiciansjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        nursejCheckBox3.setText("Nurse");
        nursejCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nursejCheckBox3ActionPerformed(evt);
            }
        });
        add(nursejCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        surgeonjCheckBox4.setText("Surgeon");
        surgeonjCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeonjCheckBox4ActionPerformed(evt);
            }
        });
        add(surgeonjCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        pathologistjCheckBox5.setText("Pathologist");
        pathologistjCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathologistjCheckBox5ActionPerformed(evt);
            }
        });
        add(pathologistjCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        phajCheckBox6.setText("Pharmacist");
        phajCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phajCheckBox6ActionPerformed(evt);
            }
        });
        add(phajCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, -1));

        jButton2.setText("back to homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 690, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 470, 40));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 10));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Blood or Blood Product");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 290, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("What type of blood product was involved in the event");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 520, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("During what stage was the event discovered");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 440, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Involved Personnel:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, -1));

        locationjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationjComboBox1ActionPerformed(evt);
            }
        });
        add(locationjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 210, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("This event occured at:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 210, -1));

        jLabel1.setText("(Please select one box)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jLabel2.setText("(Please select one box)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel3.setText("(Please select related personnels)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void adminstrationjCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminstrationjCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminstrationjCheckBox1ActionPerformed

    private void PhysiciansjCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysiciansjCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhysiciansjCheckBox2ActionPerformed

    private void nursejCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nursejCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nursejCheckBox3ActionPerformed

    private void surgeonjCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeonjCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeonjCheckBox4ActionPerformed

    private void pathologistjCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathologistjCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathologistjCheckBox5ActionPerformed

    private void phajCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phajCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phajCheckBox6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (PhysiciansjCheckBox2.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PHYSICIAN);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (nursejCheckBox3.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.NURESE);
            //doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (pathologistjCheckBox5.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PATHOLOGIST);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (phajCheckBox6.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PHARMACIST);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (adminstrationjCheckBox1.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.ADMINSTRATION);
            //doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (surgeonjCheckBox4.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.SURGEON);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }

       
        if (wholejCheckBox5.isSelected()) {
            workRequest.setBloodtyep(Blood.WHOLE_BLOOD);
        }
        if (redjCheckBox2.isSelected()) {
            workRequest.setBloodtyep(Blood.RED_BLOOD_CELL);
        }
        if (rhlgjCheckBox4.isSelected()) {
            workRequest.setBloodtyep(Blood.RHLG);
        }
        if (plasmajCheckBox3.isSelected()) {
            workRequest.setBloodtyep(Blood.PLASMA);
        }

        
        
        
         workRequest.setLocation((String) locationjComboBox1.getSelectedItem());
         
        if (productjCheckBox1.isSelected()) {
            workRequest.setBloodstage(Blood.PRODUCT);
        }
        if (postjCheckBox7.isSelected()) {
            workRequest.setBloodstage(Blood.POST_TRANSFUSION);
        }
        if (samplejCheckBox6.isSelected()) {
            workRequest.setBloodstage(Blood.SAMPLE);
        }

        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof ServiceOrganization) {
                o.getWorkQueue().getWorkRequestList().add(workRequest);
            }
        }
        ua.getWorkQueue().getWorkRequestList().add(workRequest);
        JOptionPane.showMessageDialog(null, "The report has been submitted");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DoctorHomepageAreaJPanel doctorReportMedicationJPanel = new DoctorHomepageAreaJPanel(container, ua,o,e,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("doctorReportMedicationJPanel", doctorReportMedicationJPanel);
        cl.next(container);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void locationjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationjComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PhysiciansjCheckBox2;
    private javax.swing.JCheckBox adminstrationjCheckBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox locationjComboBox1;
    private javax.swing.JCheckBox nursejCheckBox3;
    private javax.swing.JCheckBox pathologistjCheckBox5;
    private javax.swing.JCheckBox phajCheckBox6;
    private javax.swing.JCheckBox plasmajCheckBox3;
    private javax.swing.JCheckBox postjCheckBox7;
    private javax.swing.JCheckBox productjCheckBox1;
    private javax.swing.JCheckBox redjCheckBox2;
    private javax.swing.JCheckBox rhlgjCheckBox4;
    private javax.swing.JCheckBox samplejCheckBox6;
    private javax.swing.JCheckBox surgeonjCheckBox4;
    private javax.swing.JCheckBox wholejCheckBox5;
    // End of variables declaration//GEN-END:variables
}
