/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ServiceOrganization;
import Business.UserAccount.UserAccount;
import Business.Util.Location;
import Business.Util.Surgery;
import Business.UtilPersonnel.ErrorPerson;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class DLevel2SurgeryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DLevel2SurgeryJPanel
     */
    JPanel container;
    WorkRequest workRequest;
    Enterprise e;
    UserAccount ua;
    Organization o;
    EcoSystem ecoSystem;

    public DLevel2SurgeryJPanel(JPanel container, WorkRequest workRequest1, Enterprise e, UserAccount ua, Organization o,
            EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.workRequest = workRequest1;
        this.e = e;
        this.ua = ua;
        this.o = o;
        this.ecoSystem = ecoSystem;
        populateEvent();
        populateLocation();
        int progress = 100;
        jProgressBar1.setValue(progress);

    }

    private void populateLocation() {
        locationjComboBox1.removeAllItems();
        locationjComboBox1.addItem(Location.EMERGENCY);
        locationjComboBox1.addItem(Location.LABORATORY);
        locationjComboBox1.addItem(Location.OR);
        locationjComboBox1.addItem(Location.OUTPATIEN);
        locationjComboBox1.addItem(Location.PHARMACY);
        locationjComboBox1.addItem(Location.WARD);
    }

    private void populateDetail() {
        charajComboBox1.removeAllItems();
        String type = (String) eventjComboBox1.getSelectedItem();
        if (type.equals(Surgery.Surgery)) {
            charajComboBox1.addItem(Surgery.SURGICAL_SITE_INFECTION);
            charajComboBox1.addItem(Surgery.BURN_OPERATING_ROOM_FIRE);
            charajComboBox1.addItem(Surgery.INCORRECT_SURGICAL_PROCEDURE);
            charajComboBox1.addItem(Surgery.LATROGENIC_PNEUMOTHORAX);

        }
        if (type.equals(Surgery.Anesthesia)) {
            charajComboBox1.addItem(Surgery.DENTAL_INJURY);
            charajComboBox1.addItem(Surgery.OCULAR_INJURY);
            charajComboBox1.addItem(Surgery.PERIPHERAL_NERVE_INJURY);
            charajComboBox1.addItem(Surgery.MALIGNANT_HYPERTHERMIA);
        }
    }

    private void populateEvent() {
        eventjComboBox1.removeAllItems();
        eventjComboBox1.addItem(Surgery.Anesthesia);
        eventjComboBox1.addItem(Surgery.Surgery);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventjComboBox1 = new javax.swing.JComboBox();
        carjCheckBox1 = new javax.swing.JCheckBox();
        cenjCheckBox2 = new javax.swing.JCheckBox();
        renaljCheckBox3 = new javax.swing.JCheckBox();
        resCheckBox4 = new javax.swing.JCheckBox();
        charajComboBox1 = new javax.swing.JComboBox();
        phajCheckBox6 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        nursejCheckBox3 = new javax.swing.JCheckBox();
        pathologistjCheckBox5 = new javax.swing.JCheckBox();
        surgeonjCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        adminstrationjCheckBox1 = new javax.swing.JCheckBox();
        PhysiciansjCheckBox2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        locationjComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventjComboBox1ActionPerformed(evt);
            }
        });
        add(eventjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 208, -1));

        carjCheckBox1.setText("Cardiac or circulatory event");
        add(carjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        cenjCheckBox2.setText("Central nervous system event");
        add(cenjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        renaljCheckBox3.setText("Renal failure");
        add(renaljCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        resCheckBox4.setText("Respiratory failure");
        add(resCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        add(charajComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 215, -1));

        phajCheckBox6.setText("Pharmacist");
        phajCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phajCheckBox6ActionPerformed(evt);
            }
        });
        add(phajCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Involved Personnel:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 184, -1));

        nursejCheckBox3.setText("Nurse");
        nursejCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nursejCheckBox3ActionPerformed(evt);
            }
        });
        add(nursejCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        pathologistjCheckBox5.setText("Pathologist");
        pathologistjCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathologistjCheckBox5ActionPerformed(evt);
            }
        });
        add(pathologistjCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        surgeonjCheckBox4.setText("Surgeon");
        surgeonjCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeonjCheckBox4ActionPerformed(evt);
            }
        });
        add(surgeonjCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, -1, -1));

        adminstrationjCheckBox1.setText("Adminstration");
        adminstrationjCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminstrationjCheckBox1ActionPerformed(evt);
            }
        });
        add(adminstrationjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        PhysiciansjCheckBox2.setText("Physicians");
        PhysiciansjCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysiciansjCheckBox2ActionPerformed(evt);
            }
        });
        add(PhysiciansjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jButton3.setText("back to homepage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Surgery or Anesthesia");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 232, 46));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 470, 40));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 690, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("What best describes the event? ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 367, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Which of the following major complications occurred?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Which of the following best characterizes the  surgery/anesthesia?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 690, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("This event occured at:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 210, -1));

        locationjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationjComboBox1ActionPerformed(evt);
            }
        });
        add(locationjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 210, -1));

        jLabel6.setText("(Please select related personnels)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void eventjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventjComboBox1ActionPerformed
        // TODO add your handling code here:
        populateDetail();


    }//GEN-LAST:event_eventjComboBox1ActionPerformed

    private void phajCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phajCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phajCheckBox6ActionPerformed

    private void nursejCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nursejCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nursejCheckBox3ActionPerformed

    private void pathologistjCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathologistjCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathologistjCheckBox5ActionPerformed

    private void surgeonjCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeonjCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeonjCheckBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (PhysiciansjCheckBox2.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PHYSICIAN);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (nursejCheckBox3.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.NURESE);
            //doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (pathologistjCheckBox5.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PATHOLOGIST);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (phajCheckBox6.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PHARMACIST);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (adminstrationjCheckBox1.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.ADMINSTRATION);
            //doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (surgeonjCheckBox4.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.SURGEON);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }

        if (carjCheckBox1.isSelected()) {
            workRequest.setComplication(Surgery.CARDIA);
        }
        if (cenjCheckBox2.isSelected()) {
            workRequest.setComplication(Surgery.CENTRAL_NEVERVOUS);
        }
        if (resCheckBox4.isSelected()) {
            workRequest.setComplication(Surgery.RESPIRATORY);
        }
        if (renaljCheckBox3.isSelected()) {
            workRequest.setComplication(Surgery.RENAL_FAILURE);
        }

        
         workRequest.setLocation((String) locationjComboBox1.getSelectedItem());
        workRequest.setCharaofsurgery((String) charajComboBox1.getSelectedItem());
        workRequest.setSurgeryevent((String) eventjComboBox1.getSelectedItem());

        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof ServiceOrganization) {
                o.getWorkQueue().getWorkRequestList().add(workRequest);
            }
        }
        ua.getWorkQueue().getWorkRequestList().add(workRequest);
        JOptionPane.showMessageDialog(null, "The report has been submitted");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminstrationjCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminstrationjCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminstrationjCheckBox1ActionPerformed

    private void PhysiciansjCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysiciansjCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhysiciansjCheckBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DoctorHomepageAreaJPanel doctorReportMedicationJPanel = new DoctorHomepageAreaJPanel(container, ua, o, e, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("doctorReportMedicationJPanel", doctorReportMedicationJPanel);
        cl.next(container);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void locationjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationjComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PhysiciansjCheckBox2;
    private javax.swing.JCheckBox adminstrationjCheckBox1;
    private javax.swing.JCheckBox carjCheckBox1;
    private javax.swing.JCheckBox cenjCheckBox2;
    private javax.swing.JComboBox charajComboBox1;
    private javax.swing.JComboBox eventjComboBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox locationjComboBox1;
    private javax.swing.JCheckBox nursejCheckBox3;
    private javax.swing.JCheckBox pathologistjCheckBox5;
    private javax.swing.JCheckBox phajCheckBox6;
    private javax.swing.JCheckBox renaljCheckBox3;
    private javax.swing.JCheckBox resCheckBox4;
    private javax.swing.JCheckBox surgeonjCheckBox4;
    // End of variables declaration//GEN-END:variables
}
