/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ServiceOrganization;
import Business.UserAccount.UserAccount;
import Business.Util.Fall;
import Business.Util.Location;
import Business.UtilPersonnel.ErrorPerson;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class DLevel2FallJPanel extends javax.swing.JPanel {
    
    JPanel container;
    WorkRequest workRequest;
    Enterprise e;
    UserAccount ua;
    Organization o;
    EcoSystem ecoSystem;
    
    public DLevel2FallJPanel(JPanel container, WorkRequest workRequest1, Enterprise e, UserAccount ua,Organization o,
            EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.workRequest = workRequest1;
        this.e = e;
        this.ua = ua;
          this.o = o;
        this.ecoSystem = ecoSystem;
    
        int progress = 100;
       jProgressBar1.setValue(progress);
        
        populateFall();
        populateDoing();
        populateLocation();
    }
    
    
    private void populateLocation(){
        locationjComboBox1.removeAllItems();
        locationjComboBox1.addItem(Location.EMERGENCY);
        locationjComboBox1.addItem(Location.LABORATORY);
        locationjComboBox1.addItem(Location.OR);
        locationjComboBox1.addItem(Location.OUTPATIEN);
        locationjComboBox1.addItem(Location.PHARMACY);
        locationjComboBox1.addItem(Location.WARD);
    }
    
    private void populateDoing() {
        doingjComboBox1.removeAllItems();
        doingjComboBox1.addItem(Fall.AMBULATING_WITH_ASSISTANCE);
        doingjComboBox1.addItem(Fall.AMUBLATING_WITHOUT_ASSISTANCE);
        doingjComboBox1.addItem(Fall.CHANGING_POSITION);
        doingjComboBox1.addItem(Fall.NAVIGATING_BEDRAILS);
        doingjComboBox1.addItem(Fall.SHOWING_OR_BATHING);
        doingjComboBox1.addItem(Fall.REACHING_FOR_AN_ITEM);
    }

    private void populateFall() {
        falljComboBox1.removeAllItems();
        falljComboBox1.addItem(Fall.ASSISTED);
        falljComboBox1.addItem(Fall.UNASSISTED);
        falljComboBox1.addItem(Fall.UNKNOWN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        falljComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        phajCheckBox6 = new javax.swing.JCheckBox();
        PhysiciansjCheckBox2 = new javax.swing.JCheckBox();
        adminstrationjCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        surgeonjCheckBox4 = new javax.swing.JCheckBox();
        pathologistjCheckBox5 = new javax.swing.JCheckBox();
        nursejCheckBox3 = new javax.swing.JCheckBox();
        dislocationjCheckBox1 = new javax.swing.JCheckBox();
        lacerationrequiringsuturesjCheckBox2 = new javax.swing.JCheckBox();
        intracranialinjuryjCheckBox3 = new javax.swing.JCheckBox();
        fracturejCheckBox5 = new javax.swing.JCheckBox();
        notapplicablejCheckBox6 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        doingjComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        locationjComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(falljComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 316, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Involved Personnel:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 184, -1));

        phajCheckBox6.setText("Pharmacist");
        phajCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phajCheckBox6ActionPerformed(evt);
            }
        });
        add(phajCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        PhysiciansjCheckBox2.setText("Physicians");
        PhysiciansjCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysiciansjCheckBox2ActionPerformed(evt);
            }
        });
        add(PhysiciansjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        adminstrationjCheckBox1.setText("Adminstration");
        adminstrationjCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminstrationjCheckBox1ActionPerformed(evt);
            }
        });
        add(adminstrationjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, -1, -1));

        surgeonjCheckBox4.setText("Surgeon");
        surgeonjCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeonjCheckBox4ActionPerformed(evt);
            }
        });
        add(surgeonjCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        pathologistjCheckBox5.setText("Pathologist");
        pathologistjCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathologistjCheckBox5ActionPerformed(evt);
            }
        });
        add(pathologistjCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        nursejCheckBox3.setText("Nurse");
        nursejCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nursejCheckBox3ActionPerformed(evt);
            }
        });
        add(nursejCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        dislocationjCheckBox1.setText("Dislocation");
        add(dislocationjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        lacerationrequiringsuturesjCheckBox2.setText("Laceration requiring sutures");
        add(lacerationrequiringsuturesjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        intracranialinjuryjCheckBox3.setText("Intracranial injury");
        add(intracranialinjuryjCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        fracturejCheckBox5.setText("Fracture");
        add(fracturejCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        notapplicablejCheckBox6.setText("Not applicable");
        notapplicablejCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notapplicablejCheckBox6ActionPerformed(evt);
            }
        });
        add(notapplicablejCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Prior to the fall, what was the patient doing or trying to do?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        add(doingjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 316, -1));

        jButton2.setText("back to homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("What type of physicial iInjury caused by this event");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 490, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Was the fall unassisted or assisted?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 340, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Fall");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 111, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 470, 40));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 690, 10));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("This event occured at:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 210, -1));

        locationjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationjComboBox1ActionPerformed(evt);
            }
        });
        add(locationjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 210, -1));

        jLabel6.setText("(Please select one box)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel7.setText("(Please select one)");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel8.setText("(Please select related personnels)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void phajCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phajCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phajCheckBox6ActionPerformed

    private void PhysiciansjCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysiciansjCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhysiciansjCheckBox2ActionPerformed

    private void adminstrationjCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminstrationjCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminstrationjCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (PhysiciansjCheckBox2.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PHYSICIAN);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (nursejCheckBox3.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.NURESE);
            //doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (pathologistjCheckBox5.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PATHOLOGIST);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (phajCheckBox6.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.PHARMACIST);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (adminstrationjCheckBox1.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.ADMINSTRATION);
            //doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        if (surgeonjCheckBox4.isSelected()) {
            ErrorPerson ep1 = workRequest.getEpd().createPersonnel(ErrorPerson.ErrorPersonType.SURGEON);
            // doctorReport.getEpd().getErrorpersonlist().add(ep1);
        }
        
        if (fracturejCheckBox5.isSelected()) {
            workRequest.setCauseoffall(Fall.FRACTURE);
        }
        if (dislocationjCheckBox1.isSelected()) {
            workRequest.setCauseoffall(Fall.DISLOCATION);
        }
        if (intracranialinjuryjCheckBox3.isSelected()) {
            workRequest.setCauseoffall(Fall.INTRACRANIAL_INJURY);
        }
        if (lacerationrequiringsuturesjCheckBox2.isSelected()) {
            workRequest.setCauseoffall(Fall.LACERATION_REQUIRING);
        }
        if (notapplicablejCheckBox6.isSelected()) {
            workRequest.setCauseoffall(Fall.NOT_APPLICABLE);        
        }
        
        
        
        
         workRequest.setLocation((String) locationjComboBox1.getSelectedItem());
        workRequest.setFalldoing((String) doingjComboBox1.getSelectedItem());
        workRequest.setAssisted((String) falljComboBox1.getSelectedItem());
        
        for (Organization on : e.getOrganizationDirectory().getOrganizationList()) {
            if (on instanceof ServiceOrganization) {
                on.getWorkQueue().getWorkRequestList().add(workRequest);
            }
        }
        
        JOptionPane.showMessageDialog(null, "The report has been submitted");

        ua.getWorkQueue().getWorkRequestList().add(workRequest);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void surgeonjCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeonjCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeonjCheckBox4ActionPerformed

    private void pathologistjCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathologistjCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathologistjCheckBox5ActionPerformed

    private void nursejCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nursejCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nursejCheckBox3ActionPerformed

    private void notapplicablejCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notapplicablejCheckBox6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_notapplicablejCheckBox6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DoctorHomepageAreaJPanel doctorReportMedicationJPanel = new DoctorHomepageAreaJPanel(container, ua,o,e,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("doctorReportMedicationJPanel", doctorReportMedicationJPanel);
        cl.next(container);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void locationjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationjComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PhysiciansjCheckBox2;
    private javax.swing.JCheckBox adminstrationjCheckBox1;
    private javax.swing.JCheckBox dislocationjCheckBox1;
    private javax.swing.JComboBox doingjComboBox1;
    private javax.swing.JComboBox falljComboBox1;
    private javax.swing.JCheckBox fracturejCheckBox5;
    private javax.swing.JCheckBox intracranialinjuryjCheckBox3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JCheckBox lacerationrequiringsuturesjCheckBox2;
    private javax.swing.JComboBox locationjComboBox1;
    private javax.swing.JCheckBox notapplicablejCheckBox6;
    private javax.swing.JCheckBox nursejCheckBox3;
    private javax.swing.JCheckBox pathologistjCheckBox5;
    private javax.swing.JCheckBox phajCheckBox6;
    private javax.swing.JCheckBox surgeonjCheckBox4;
    // End of variables declaration//GEN-END:variables
}
