/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class DoctorHomepageAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorHomepageAreaJPanel
     */
    JPanel container;
    UserAccount ua;  
    DoctorOrganization dorganization;
    Enterprise e;
    EcoSystem ecoSystem;

    public DoctorHomepageAreaJPanel(JPanel j, UserAccount ua, Organization og, Enterprise e, EcoSystem ecoSystem) {
        initComponents();
        container = j;
        this.ua = ua;
        this.dorganization = (DoctorOrganization) og;
        this.e = e;
        this.ecoSystem = ecoSystem;
        pupulateText();
    }

    private void pupulateText() {
        unamejTextField2.setText(ua.getUserName());
        //namejTextField3.setText(ua.getDoctor().getDoctorname());
        hosnamejTextField4.setText(e.getOrgName());
        rolejTextField5.setText(ua.getRole().toString());    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unamejTextField2 = new javax.swing.JTextField();
        hosnamejTextField4 = new javax.swing.JTextField();
        rolejTextField5 = new javax.swing.JTextField();
        reportjButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkjButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 232, -1, -1));
        add(unamejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 220, -1));
        add(hosnamejTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 220, -1));
        add(rolejTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 220, -1));

        reportjButton1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        reportjButton1.setText("Start Report");
        reportjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportjButton1ActionPerformed(evt);
            }
        });
        add(reportjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Hospital name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Role:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Report - Doctor Work Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        checkjButton2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        checkjButton2.setText("Check Report");
        checkjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkjButton2ActionPerformed(evt);
            }
        });
        add(checkjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Your Information");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorRole/Screen Shot 2013-12-10 at 4.44.26 PM.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 420, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void reportjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportjButton1ActionPerformed
        // TODO add your handling code here:
        DStartReportJPanel drejp = new DStartReportJPanel(container, ua, dorganization, e, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("dirjp", drejp);
        cl.next(container);
    }//GEN-LAST:event_reportjButton1ActionPerformed

    private void checkjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkjButton2ActionPerformed
        // TODO add your handling code here:
        DCheckStatusJPanel checkStatuJPanel = new DCheckStatusJPanel(container, ua, dorganization, e, ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("setMessageJPanel", checkStatuJPanel);
        cl.next(container);
    }//GEN-LAST:event_checkjButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkjButton2;
    private javax.swing.JTextField hosnamejTextField4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton reportjButton1;
    private javax.swing.JTextField rolejTextField5;
    private javax.swing.JTextField unamejTextField2;
    // End of variables declaration//GEN-END:variables
}
