/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.Util.ErrorUtil;
import Business.WorkQueue.DoctorReport;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class DoctorReportErrorlevel1JPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorReportErrorlevel1JPanel
     */
    
    JPanel container;
    UserAccount ua;
    DoctorOrganization doctorOrganization;
    Enterprise e;
    DoctorReport workRequest;
    EcoSystem ecoSystem;
    
   // DoctorRequest doctorRequest;
    
    public DoctorReportErrorlevel1JPanel(JPanel container,UserAccount ua,DoctorOrganization doctorOrganization,Enterprise e,WorkRequest workRequest1, EcoSystem ecoSystem) {
        initComponents();
        this.workRequest = (DoctorReport) workRequest1;
        this.container = container;
        this.ua = ua;
        this.doctorOrganization = doctorOrganization;
        this.e = e;
        this.ecoSystem = ecoSystem;
        
        int progress= 50;
        jProgressBar1.setValue(progress);
        idjTextField2.setText(String.valueOf(workRequest.getId()));
      
                
    }
    
    
          
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incidentjButton2 = new javax.swing.JButton();
        nearmissjButton3 = new javax.swing.JButton();
        unsafejButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        idjTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incidentjButton2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        incidentjButton2.setText("Incident");
        incidentjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidentjButton2ActionPerformed(evt);
            }
        });
        add(incidentjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 121, 40));

        nearmissjButton3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nearmissjButton3.setText("Near Miss");
        nearmissjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearmissjButton3ActionPerformed(evt);
            }
        });
        add(nearmissjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 121, 40));

        unsafejButton4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        unsafejButton4.setText("Unsafe Condition");
        unsafejButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unsafejButton4ActionPerformed(evt);
            }
        });
        add(unsafejButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Level 1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 220, -1));

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 27, -1, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        jLabel5.setText("Report NO.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 80, -1));

        idjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextField2ActionPerformed(evt);
            }
        });
        add(idjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 80, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 840, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 840, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 840, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 5.05.45 PM.png"))); // NOI18N
        jLabel10.setText("Report NO.");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 200, 130));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 5.01.59 PM.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 190, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 4.49.21 PM.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 190, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText(" whether or not the patient was harmed.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 892, 29));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("A patient safety event that reached the patient,");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 85, 892, 29));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 840, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("A patient safety event that did not reach the patient.");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 528, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Any circumstance that increases");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 720, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("the probability of a patient safety event.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 720, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void incidentjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentjButton2ActionPerformed
        // TODO add your handling code here:    
        
        workRequest.setLevel1(ErrorUtil.INCIDENT);
        
        DLevel1IncidentJPanel doctorReportError3JPanel = new DLevel1IncidentJPanel(container, workRequest,e,ua,doctorOrganization,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", doctorReportError3JPanel);
        cl.next(container);
        
    }//GEN-LAST:event_incidentjButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nearmissjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearmissjButton3ActionPerformed
        // TODO add your handling code here:
        
        workRequest.setLevel1(ErrorUtil.NEAR_MISS);
        DLevel1NearMissPanel doctorReportError3JPanel = new DLevel1NearMissPanel(container, workRequest,e,ua,doctorOrganization,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", doctorReportError3JPanel);
        cl.next(container);
    }//GEN-LAST:event_nearmissjButton3ActionPerformed

    private void unsafejButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsafejButton4ActionPerformed
        // TODO add your handling code here:
        workRequest.setLevel1(ErrorUtil.UNSAFE_CONDITION);
        
        DLevel1UnsafeJPanel doctorReportError3JPanel = new DLevel1UnsafeJPanel(container, workRequest,e,ua,doctorOrganization,ecoSystem);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", doctorReportError3JPanel);
        cl.next(container);
        
        
    }//GEN-LAST:event_unsafejButton4ActionPerformed

    private void idjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idjTextField2;
    private javax.swing.JButton incidentjButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton nearmissjButton3;
    private javax.swing.JButton unsafejButton4;
    // End of variables declaration//GEN-END:variables
}
