/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Util.Source;
import Business.WorkQueue.DoctorReport;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class DStartReportJPanel extends javax.swing.JPanel {

    JPanel container;
    UserAccount ua;
    DoctorOrganization doctorOrganization;
    EcoSystem business;
    Enterprise e;

    /**
     * Creates new form DoctorWorkareaJPanel
     */
    public DStartReportJPanel(JPanel container, UserAccount ua, Organization org, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.doctorOrganization = (DoctorOrganization) org;
        this.e = enterprise;
        business = ecoSystem;
        int progress = 25;
        jProgressBar1.setValue(progress);
        
        populateInfo();
        
    }

    private void populateInfo() {
        if(ua.getDoctor().getEmail()!=null){
            emailjTextField3.setText(ua.getDoctor().getEmail());
            phonejTextField2.setText(String.valueOf(ua.getDoctor().getPhone()));
        }if(ua.getDoctor().getEmail()==null){
            emailjTextField3.setText("");
            phonejTextField2.setText("");
           
        }
       
    }

   
    private void createReport() {

        DoctorReport doctorReport = new DoctorReport();
        // doctorReport.setTest(addinfojTextField1.getText());
        // doctorReport.setMessage(addinfojTextField1.getText());
        doctorReport.setSender(ua);
        doctorReport.setDoctorreporter(ua);
        //ua.setNetwork(doctorReport.getSenderNetwork());
        doctorReport.setStatus("Pending");
        // doctorReport.setPersonnel((String) personneljComboBox2.getSelectedItem());
        //doctorReport.setLevel1((String) level1jComboBox3.getSelectedItem());
        //doctorReport.setLevel2((String) level2jComboBox2.getSelectedItem());
        Date date = jDateChooser1.getDate();
        doctorReport.setDateoferror(date);

        //doctorReport.getSenderNetwork() ;
        //doctorReport.setReportdate(null);
        if (firstjCheckBox1.isSelected()) {
            doctorReport.setSource(Source.FIRST);
        }
        if (secondjCheckBox3.isSelected()) {
            doctorReport.setSource(Source.SECOND);
        }

        try {
            doctorReport.creatTime();
        } catch (ParseException ex) {
            Logger.getLogger(DStartReportJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        doctorReport.setSenderEnterprise(e);

       // Enterprise en = doctorReport.getSenderEnterprise();
        // en.getIssuesWorkRequestList().add(doctorReport);
        Doctor doctor = ua.getDoctor();
        //doctor.setId(Integer.valueOf(namejTextField1.getText()));
        if (ua.getDoctor().getEmail() == null) {
            doctor.setEmail(emailjTextField3.getText());
        }

        if (ua.getDoctor().getPhone() == 0) {
            doctor.setPhone(Integer.parseInt(phonejTextField2.getText()));
        }

        DoctorReportErrorlevel1JPanel patientReportError2Panel = new DoctorReportErrorlevel1JPanel(container, ua, doctorOrganization, e, doctorReport, business);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("patientReportError2Panel", patientReportError2Panel);
        cl.next(container);

//org.getWorkQueue().getWorkRequestList().add(doctorReport);
        //idjTextField1.setText(String.valueOf(doctorReport.getId()));
        //ua.setReportnumber(doctorReport.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendrequestjButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firstjCheckBox1 = new javax.swing.JCheckBox();
        secondjCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phonejTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailjTextField3 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendrequestjButton2.setText("Next");
        sendrequestjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendrequestjButton2ActionPerformed(evt);
            }
        });
        add(sendrequestjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Select the Date of Medical Error:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 340, -1));

        firstjCheckBox1.setText("First Hand");
        firstjCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstjCheckBox1ActionPerformed(evt);
            }
        });
        add(firstjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 120, -1));

        secondjCheckBox3.setText("Second Hand");
        secondjCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondjCheckBox3ActionPerformed(evt);
            }
        });
        add(secondjCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Resource:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 130, -1));

        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 200, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Please fill the personal information");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 360, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("The contact information will help us contact you for futher information");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Phone:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        phonejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonejTextField2ActionPerformed(evt);
            }
        });
        add(phonejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Email:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        emailjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextField3ActionPerformed(evt);
            }
        });
        add(emailjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, -1));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/Screen Shot 2013-12-10 at 6.17.30 PM.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 480, 40));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 650, 700, 10));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Your information will be confidential.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void sendrequestjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendrequestjButton2ActionPerformed

        createReport();

        // SetMessageJPanel setMessageJPanel = new SetMessageJPanel(container, ua, e.getOrganizationDirectory(), e, business);
        // CardLayout cl = (CardLayout) container.getLayout();
        // container.add("setMessageJPanel", setMessageJPanel);
        //cl.next(container);
    }//GEN-LAST:event_sendrequestjButton2ActionPerformed

    private void firstjCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstjCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstjCheckBox1ActionPerformed

    private void secondjCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondjCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondjCheckBox3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void phonejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonejTextField2ActionPerformed

    private void emailjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailjTextField3;
    private javax.swing.JCheckBox firstjCheckBox1;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField phonejTextField2;
    private javax.swing.JCheckBox secondjCheckBox3;
    private javax.swing.JButton sendrequestjButton2;
    // End of variables declaration//GEN-END:variables
}
