/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces.Service;

import Business.Organization.ServiceOrganization;
import Business.Report.ReporttoEnter;
import Business.Util.ErrorUtil;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aki
 */
public class BloodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodJPanel
     */
    JPanel container;
    ServiceOrganization serviceOrganization;

    public BloodJPanel(JPanel container, ServiceOrganization serviceOrganization) {
        initComponents();
        this.container = container;
        this.serviceOrganization = serviceOrganization;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for(ReporttoEnter reporttoEnter:serviceOrganization.getReporttoEnterDir().getReporttoEnterList()){
            if(reporttoEnter.getLevel2().equals(ErrorUtil.BLOOD_OR_BLOOD_PRODUCT)){
                Object[] row = new Object[1];
                row[0] = reporttoEnter;
                model.addRow(row);
                
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fjTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sjTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        typejTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stagejTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        personneljTextField1 = new javax.swing.JTextField();
        timesjTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        respondjTextArea2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        locationjTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Report of Blood Product Error from Government");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Respond from government");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));
        add(fjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Report History");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("First");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Second");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));
        add(sjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 90, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("This type of blood is reported most frequently :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 30));
        add(typejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 160, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("This stage is reported most frequently: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        add(stagejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Report date"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 400));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Source:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("This knid of Personnel is reported most frequently:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        personneljTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personneljTextField1ActionPerformed(evt);
            }
        });
        add(personneljTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 170, -1));

        timesjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesjTextField2ActionPerformed(evt);
            }
        });
        add(timesjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 90, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Times:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        respondjTextArea2.setColumns(20);
        respondjTextArea2.setRows(5);
        jScrollPane1.setViewportView(respondjTextArea2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 360, 110));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("This kind of event most likely occure ar:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 330, -1));
        add(locationjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        } else{
            ReporttoEnter enter = (ReporttoEnter) jTable1.getValueAt(selectedRow, 0);
            fjTextField2.setText(String.valueOf(enter.getFirst()));
            sjTextField3.setText(String.valueOf(enter.getSecond()));
            timesjTextField2.setText(String.valueOf(enter.getMaxofperson()));
            personneljTextField1.setText(enter.getErrorperonstring());
             locationjTextField1.setText(enter.getMostLocation());
            
            respondjTextArea2.setText(enter.getRespond());
            typejTextField1.setText(enter.getBloodtype());
            stagejTextField2.setText(enter.getBloodstage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timesjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timesjTextField2ActionPerformed

    private void personneljTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personneljTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personneljTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fjTextField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField locationjTextField1;
    private javax.swing.JTextField personneljTextField1;
    private javax.swing.JTextArea respondjTextArea2;
    private javax.swing.JTextField sjTextField3;
    private javax.swing.JTextField stagejTextField2;
    private javax.swing.JTextField timesjTextField2;
    private javax.swing.JTextField typejTextField1;
    // End of variables declaration//GEN-END:variables
}
