/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces.Service;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aki
 */
public class HandlereportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HandlereportJPanel
     */
    JPanel container;
    Enterprise enterprise;
    WorkRequest workRequest;
    EcoSystem ecoSystem;
    UserAccount ua;

    public HandlereportJPanel(JPanel container, WorkRequest workRequest, EcoSystem ecoSystem, Enterprise enterprise1, UserAccount ua) {
        initComponents();
        this.container = container;
        this.workRequest = workRequest;
        this.ecoSystem = ecoSystem;
        enterprise = enterprise1;
        this.ua = ua;
      
        enterprisejTextField2.setText(workRequest.getSenderEnterprise().getOrgName());
        dateoferrorjTextField2.setText(workRequest.getDateoferror().toString());
       // populateNetworkCombox();
        // workRequest.setSenderEnterprise(enterprise);

    }

    //private void populateNetworkCombox() {
      //  for (Network network : ecoSystem.getNetworkList()) {
        //    netjComboBox1.addItem(network);

        //}

    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enterprisejTextField2 = new javax.swing.JTextField();
        dateoferrorjTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resjTextArea1 = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText(" Service center Work Area--Handle report");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jButton4.setText("<<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton5.setText("Respond to reporter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel6.setText("Respond");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 24));

        jLabel8.setText("Hospital name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 24));

        enterprisejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisejTextField2ActionPerformed(evt);
            }
        });
        add(enterprisejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 226, -1));

        dateoferrorjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateoferrorjTextField2ActionPerformed(evt);
            }
        });
        add(dateoferrorjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 226, -1));

        jLabel9.setText("Date of event");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 24));

        resjTextArea1.setColumns(20);
        resjTextArea1.setRows(5);
        jScrollPane1.setViewportView(resjTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        container.remove(this);
        CardLayout cl = (CardLayout) container.getLayout();
        cl.previous(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        
        workRequest.setRespond(resjTextArea1.getText());
        workRequest.setStatus("Respond to reporter");
        // workRequest.setSenderEnterprise(enterprise);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void enterprisejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterprisejTextField2ActionPerformed

    private void dateoferrorjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateoferrorjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateoferrorjTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateoferrorjTextField2;
    private javax.swing.JTextField enterprisejTextField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resjTextArea1;
    // End of variables declaration//GEN-END:variables
}
