/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.NetWork.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterfaces.Register.RegisterJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Aki
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    EcoSystem system;
    private DB4OUtil dB4OUtil = new DB4OUtil();

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        //system = ConfigureASystem.configureABusiness();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        userNameJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        registerjButton2 = new javax.swing.JButton();
        logoutjButton3 = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        registerjButton2.setText("Register");
        registerjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButton2ActionPerformed(evt);
            }
        });

        logoutjButton3.setText("Log out");
        logoutjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, logoutjButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(passwordField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .add(userNameJTextField)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, registerjButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(userNameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(passwordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(registerjButton2)
                .add(18, 18, 18)
                .add(logoutjButton3)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//video 34,35,36!!!!
        // Get user name
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().validateUserAccount(userName, password);
        Enterprise inEnterprisee = null;
        Organization inOrganization = null;

        if (userAccount == null) {
            //go inside each network to check each enterprise
            for (Network network : system.getNetworkList()) {
                //check against each enterprise
                for (Enterprise enterprise : network.getEd().getEnterprisesList()) {
                    userAccount = enterprise.getUserAccountDirectory().validateUserAccount(userName, password);
                    if (userAccount == null) {
                       
                        //check each organization inside the enterprise
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = organization.getUserAccountDirectory().validateUserAccount(userName, password);
                       
                            if (userAccount != null) {
                                inEnterprisee = enterprise;
                                inOrganization = organization;
                                break;
                            }
                        }
                    } else {
                        inEnterprisee = enterprise;
                        break;
                    }
                    if (inOrganization != null)
                    {
                        break;
                    }
                }
                if (inEnterprisee != null) {
                    break;
                }
            }

        }

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "invalid");
        } else {
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().fetchPanel(container, userAccount, inOrganization, inEnterprisee, system));
            layout.next(container);

        }

        /*for (Organization organization : business.getOrganizationDirectory().getOrganizationList()){
         userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
         if (userAccount != null){
         CardLayout layout = (CardLayout) container.getLayout();
         container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, organization, business));
         layout.next(container);
         break;
            
         }
         }      
         */
        // nihar taught below
               /*userContainerJPanel.removeAll();
         for(Organization o:business.getOrganizationDirectory().getOrganizationList())
         {
         UserAccount ua=o.getUserAccountDirectory().validateUserAccount(jTextField1.getText(), jTextField2.getText());
         if(ua!=null){
         CardLayout cl=(CardLayout) userContainerJPanel.getLayout();
         userContainerJPanel.add("WorkArea",ua.getRole().fetchPanel(userContainerJPanel, ua, o, business));
         cl.next(userContainerJPanel);
         }
         }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void registerjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButton2ActionPerformed
        // TODO add your handling code here:
        RegisterJPanel registerJPanel = new RegisterJPanel(container, system);
        CardLayout cl = (CardLayout) container.getLayout();
        container.add("setMessageJPanel", registerJPanel);
        cl.next(container);
    }//GEN-LAST:event_registerjButton2ActionPerformed

    private void logoutjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButton3ActionPerformed
        // TODO add your handling code here:
        //remove the useraccount but keep the system
        container.removeAll();
        userNameJTextField.setText("");
        passwordField.setText("");
        //everytime you log out, store the system into db40
        dB4OUtil.storeSystem(system);
        //if you close your application without logout
        //you will lost all the information you modified

    }//GEN-LAST:event_logoutjButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutjButton3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerjButton2;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
